spring:
  mongodb:
    uri: ${MONGODB_URI}
    database: bookview

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: https://bookview.duckdns.org/login/oauth2/code/google
            scope:
              - profile
              - email
  web:
    error:
      include-message: never
      include-stacktrace: never

server:
  port: 8088
  servlet:
    session:
      cookie:
        http-only: true
        secure: true # HTTPS 필수
        same-site: strict
  compression:
    enabled: true

logging:
  level:
    root: INFO
    com.woocurlee.bookview: INFO
  file:
    name: /var/log/bookview/application.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

kakao:
  api:
    key: ${KAKAO_API_KEY}
